import { createNewGame, type NewPlayerSpec } from "../../../src/game/gameState.ts";
import { authenticateDevice } from "../_shared/auth.ts";
import { parseMutationContext, writeMaintenanceEnabled } from "../_shared/mutation.ts";
import { persistTurnBatch } from "../_shared/persist.ts";
import { corsHeaders, errorResponse, jsonResponse, supabaseAdmin } from "../_shared/supabaseAdmin.ts";
import { runBotTurnsUntilHumanOrOver } from "../_shared/botLoop.ts";
Deno.serve(async(req)=>{ if(req.method==="OPTIONS") return new Response("ok",{headers:corsHeaders()});
  if(writeMaintenanceEnabled()) return errorResponse("MAINTENANCE","Spielaktionen sind kurz pausiert. Bitte versuche es gleich erneut.",503);
  try { const body=await req.json(); const context=parseMutationContext(body,false); const {deviceId,sessionToken}=body; const admin=supabaseAdmin(); const device=await authenticateDevice(admin,deviceId,sessionToken);
    const {data:room}=await admin.from("rooms").select("*").eq("room_id",device.roomId).single();
    if(room.host_device_id!==device.deviceId) return errorResponse("NOT_HOST","Nur der Host kann die nächste Runde starten.",403);
    if(room.status!=="FINISHED") return errorResponse("ROUND_NOT_FINISHED","Die aktuelle Runde läuft noch.",409);
    const {data:players,error}=await admin.from("players").select("*").eq("room_id",device.roomId).order("seat_index",{ascending:true}); if(error) throw error;
    if(!players||players.length<2) return errorResponse("NOT_ENOUGH_PLAYERS","Mindestens 2 Spieler nötig.",400);
    const specs:NewPlayerSpec[]=players.map((p)=>({playerId:p.player_id,displayName:p.display_name,type:p.player_type,avatar:p.avatar??undefined,botStrategyLevel:p.bot_strategy_level??undefined}));
    let state=createNewGame(device.roomId,specs); const botResult=await runBotTurnsUntilHumanOrOver(admin,state); state=botResult.state; const roomStatus=state.phase==="GAME_OVER"?"FINISHED":"PLAYING";
    const persisted=await persistTurnBatch(admin,state,{transitionMode:"NEXT_ROUND",expectedGameId:context.expectedGameId,expectedVersion:context.expectedVersion,batchFromVersion:0,actionId:context.actionId,roomStatus,winnerPlayerId:state.winnerPlayerId,events:botResult.events});
    return jsonResponse({ok:true,batch:persisted.batch,gameId:state.gameId,version:state.version});
  } catch(err){ const code=err instanceof Error?err.message:"SERVER_ERROR"; if(code==="MISSING_REQUIRED_FIELDS"||code==="INVALID_EXPECTED_STATE") return errorResponse(code,"Bitte lade die Seite neu.",400); return errorResponse("SERVER_ERROR",String(err),500); }
});
